# 데이터 시각화 관련 ipython 프로그램

2023 voice 전람회 인지실험 관련 시각화 툴

In [1]:
#-*-coding:utf-8-*-
import os
import numpy as np
import matplotlib
from  matplotlib import pyplot as plt
%matplotlib qt
from jamo import h2j, j2hcj
import matplotlib.colors as mcolors
import matplotlib.ticker as mticker
matplotlib.rcParams['font.family'] ='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] =False

## <b> Data Load </b>

In [2]:
import glob
print(os.getcwd())
path = '.\\data\\*'
file_list = glob.glob(path)
file_list = [file for file in file_list if file.endswith('.txt')]

files = list(map(lambda fileName:open(fileName,'rt', encoding='UTF8'),file_list))

c:\Users\dddde\OneDrive\바탕 화면\개발\Python\2023전람회\dataviz


In [3]:
def word2jamo(word):
  WORD=[]
  for i in word:
    WORD.append(list(j2hcj(h2j(i))))
  return WORD

In [5]:
numVowel = 8
numF1, numF2 = 6, 5
numf0 = 3
vowels = {'ㅣ':0,'ㅡ':1,'ㅜ':2,'ㅔ':3,'ㅓ':4,'ㅗ':5,'ㅐ':6,'ㅏ':7}
num2vowels = dict(zip(vowels.values(),vowels.keys()))

db = np.zeros((numf0,numVowel,numF1,numF2))
print(np.array(db).shape)
for i in range(numVowel):
  for file in files:
    for y,line in enumerate(file.readlines()):
      line = line.replace(',',' ')
      for x,context in enumerate(line.split()):
        t = context[0]
        if t not in vowels:t = word2jamo(t)[0][1]
        db[y//7][vowels[t]][y%7][x] += 1

(3, 8, 6, 5)


In [23]:
A = db.flatten()
numbers = np.zeros(100)
maxn =0
for i in range(1,100):
  numbers[i] = (A==i).sum()
  if numbers[i]>0: maxn=i
plt.plot(numbers)
print(maxn)

5


## <b> Data Viz </b>

In [7]:
size = 55
x = [500,800,1280,2000,3500]
y = [200,300,450,680,1000,1200]
pitch = [100,150,200]
color = list(mcolors.TABLEAU_COLORS.keys())
X,Y = np.meshgrid(x,y)

In [8]:
def Dataviz(npitch, nvowel):
  plt.figure()
  plt.title(f"pitch : {pitch[npitch]} / vowel : {num2vowels[nvowel]}")
  plt.xticks(x)
  plt.yticks(y)
  plt.scatter(x=X,y=Y,s=size*db[npitch][nvowel],c=mcolors.TABLEAU_COLORS[color[nvowel]])
  plt.show()
  
for p in range(numf0):
  for n in range(numVowel):
    Dataviz(p,n)

C:\Users\dddde\AppData\Local\Temp\ipykernel_12240\3101325198.py:2: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()


In [41]:
dx = 0.97
dy = 0.97
xx = [-3, -1, 1, 3, -3, -1, 1, 3]
yy = [1, 1, 1, 1, -1, -1, -1, -1]
size = 55
x = np.array([500,800,1280,2000,3500])
y = np.array([200,300,450,680,1000,1200])
pitch = [100,150,200]
color = list(mcolors.TABLEAU_COLORS.keys())
X,Y = np.meshgrid(x,y)
plt.figure()
plt.xticks(x)
plt.yticks(y)
plt.gca().invert_yaxis()
plt.gca().invert_xaxis()
plt.gca().set_yscale('log')
plt.gca().set_xscale('log')
plt.gca().xaxis.set_minor_formatter(mticker.ScalarFormatter())
plt.gca().yaxis.set_minor_formatter(mticker.ScalarFormatter())
plt.get_current_fig_manager().full_screen_toggle()
for vowel in list(vowels.keys()):
  a = np.zeros_like(db[0][vowels[vowel]])
  for p in range(numf0):
    a += db[p][vowels[vowel]]
  _x = x * (dx**xx[vowels[vowel]])
  _y = y * (dy**yy[vowels[vowel]])
  print(_x,_y)
  _X, _Y = np.meshgrid(_x, _y)
  plt.scatter(x=_X,y=_Y,s=60*a,c=mcolors.TABLEAU_COLORS[list(mcolors.TABLEAU_COLORS.keys())[vowels[vowel]]],alpha=1,label=vowel)
plt.legend()
plt.savefig('recognition.png')
plt.show()

Traceback (most recent call last):
  File "c:\Users\dddde\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\backends\backend_qt.py", line 468, in _draw_idle
    self.draw()
  File "c:\Users\dddde\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\backends\backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "c:\Users\dddde\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dddde\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dddde\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "c:\Users\dddde\AppData\Local\Pr

[ 547.84134076  876.54614522 1402.47383236 2191.36536306 3834.88938535] [ 194.   291.   436.5  659.6  970.  1164. ]
[ 515.46391753  824.74226804 1319.58762887 2061.8556701  3608.24742268] [ 194.   291.   436.5  659.6  970.  1164. ]
[ 485.   776.  1241.6 1940.  3395. ] [ 194.   291.   436.5  659.6  970.  1164. ]
[ 456.3365   730.1384  1168.22144 1825.346   3194.3555 ] [ 194.   291.   436.5  659.6  970.  1164. ]
[ 547.84134076  876.54614522 1402.47383236 2191.36536306 3834.88938535] [ 206.18556701  309.27835052  463.91752577  701.03092784 1030.92783505
 1237.11340206]
[ 515.46391753  824.74226804 1319.58762887 2061.8556701  3608.24742268] [ 206.18556701  309.27835052  463.91752577  701.03092784 1030.92783505
 1237.11340206]
[ 485.   776.  1241.6 1940.  3395. ] [ 206.18556701  309.27835052  463.91752577  701.03092784 1030.92783505
 1237.11340206]
[ 456.3365   730.1384  1168.22144 1825.346   3194.3555 ] [ 206.18556701  309.27835052  463.91752577  701.03092784 1030.92783505
 1237.11340206]
